version: '3.6'
services:
  admindev:
    build: 
      context: ./admin
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 2054:80

  frontdev:
    build: 
      context: ./front
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 2055:80
      
  
  