version: '3.6'
services:
  admindev:
    image: registry.gitlab.com/digitallforyou/immobilier/staging/admin:staging
    restart: always
    ports:
      - 2054:80

  frontdev:
    image: registry.gitlab.com/digitallforyou/immobilier/staging/web:staging
    env_file:
      - .env
    restart: always
    ports:
      - 2055:80