version: '3.6'
services:
  admindev:
    build: 
      context: ./admin
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 2054:80

  frontdev:
    build: 
      context: ./front
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 2055:80
      
  app:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/

  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - /back:/var/www/
      - ./back/nginx:/etc/nginx/conf.d
  
  db:
    image: mysql:5.7
    container_name: travellist-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  