FROM node:16.13.1-alpine as develop-stage

WORKDIR /admin

COPY package*.json ./

RUN yarn global add @quasar/cli

COPY . .

# build stage
FROM develop-stage as build-stage

RUN yarn

RUN quasar build

# étape de production
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /admin/dist/spa /usr/share/nginx/html
COPY config/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]