FROM node:14-alpine as develop-stage

WORKDIR /admin

COPY package*.json ./

RUN yarn global add @quasar/cli

COPY . .

# build stage
FROM develop-stage as build-stage

RUN yarn install

RUN quasar build

# étape de production
FROM nginx:stable-alpine as production-stage

COPY --from=build-stage /admin/dist/spa /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]