FROM node:latest as build-stage
WORKDIR /admin

COPY package*.json ./
COPY quasar.conf.js ./
COPY . .

RUN npm install
RUN npm install -g @vue/cli
RUN npm install -g @quasar/cli 
RUN quasar build

FROM nginx as production-stage
RUN mkdir /app
COPY --from=buildenv /admin/dist/spa /usr/share/nginx/html