FROM node:13.14-alpine as develop-stage

WORKDIR /front

COPY package*.json ./

RUN yarn global add @quasar/cli

COPY . .

# build stage
FROM develop-stage as build-stage

RUN yarn

RUN quasar build

# étape de production
FROM nginx:stable-alpine as production-stage

COPY --from=build-stage /front/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]