name: Build Containers for Prod & Push to Dockerhub

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  #Push to Digital Ocean private Registry
  pushToDORegistry:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2       
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}   
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          repository: sys33/devops
          dockerfile: front/Dockerfile.dev
          tags: admin:develop
